name: sfdx-template on push

on: [push]

jobs:
  onpush:
    runs-on: ubuntu-latest
    name: Run PMD, Format code with prettier, and Lint LWCs
    steps:
      - uses: sfdx-actions/setup-pmd@v1

      - name: "Checkout code"
        uses: actions/checkout@v2

      - name: Run Apex PMD Static (Code Analyzer)
        run: pmd -d ./force-app/main/default/classes -R category/apex/design.xml -f text

      # Cache node_modules to speed up the process
      - name: Restore node_modules cache
        id: cache-npm
        uses: actions/cache@v1
        with:
          path: node_modules
          key: npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-${{ env.cache-name }}-
            npm-

      # Install npm dependencies for Prettier and Jest
      - name: 'Install npm dependencies'
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: npm install

      # Prettier formatting
      - name: 'Code formatting verification with Prettier'
        run: npm run prettier --write --check

      #Commit prettified files if they differ from repo
      - name: Commit prettified files (if any)
        run: |
          echo ${{ github.ref }}
          git add force-app
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Prettified code!" -a | exit 0

      - name: Push prettified changes (if any)
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
